name: flutter_pdf

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:                # Importante  
    sdk: flutter
  font_awesome_flutter: ^9.2.0          # Basico
  get: ^4.6.1                           # Basico
  google_fonts: ^2.2.0                  # Basico
  cupertino_icons: ^1.0.2           
  pdf: ^3.7.1
  path_provider: ^2.0.9
  open_file: ^3.2.1
  image_picker: ^0.8.4+10

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Bold.ttf
        - asset: assets/fonts/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-SemiBold.ttf
        - asset: assets/fonts/RoadRage-Regular.ttf
